
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.2'
version_full = 'c748ab4e9b78e0410488c18fb5bbcf8da55bce3a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

